# Defines the configuration version.
# The only possible value is "2".
version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/MagaluCloud/cligen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclusions:
    # Mode of the generated files analysis.
    # Default: strict
    generated: lax
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true
    # Excluding configuration per-path, per-linter, per-text and per-source.
    rules:
      # Exclui arquivos de teste de alguns linters
      - path: _test\.go$
        linters:
          - errcheck
          - gosimple
          - govet
    # Which file paths to exclude: they will be analyzed, but issues from them won't be reported.
    # "/" will be replaced by the current OS file path separator to properly work on Windows.
    paths:
      - "^base-cli/.*"
      - "^tmp-cli/.*"
      - "^tmp-sdk/.*"
      - "^base-cli-gen/.*"
      - "^tmp-cli copy.*/.*"
      - ".*\\.pb\\.go$"

